name: "Steam Workshop Workflow"
author: "TechnologicNick"
description: "Update a README with information about Steam Workshop items"

inputs:
  steam_api_key:
    description: "Steam API key used to interact with the Steam web API"
    required: true
    default: ${{ secrets.STEAM_API_KEY }}
  comment_tag:
    description: "The comment tags to look for: <!-- comment_tag:START --> and <!-- comment_tag:END -->"
    required: false
    default: "WORKSHOP-SHOWCASE"
  readme_file:
    description: "The path to the README file"
    required: false
    default: "README.md"
  image_path:
    description: "The path to the folder of generated images"
    required: false
    default: "media/steam-workshop-workflow/"
  github_raw_path:
    description: "The path to the raw files, example: /TechnologicNick/TechnologicNick/raw/master/"
    required: true
    default: ${{ "/" + github.repository + "/raw/master/" }}
  workshop_items:
    description: "Steam Workshop items and optionally URLs to their source"
    required: true

runs:
  using: "node12"
  main: "index.js"