name: "Steam Workshop Workflow"
author: "TechnologicNick"
description: "Update a README with information about Steam Workshop items"

input:
  github_token:
    description: "GitHub access token with Repo scope"
    required: false
    default: ${{ github.token }}
  steam_api_key:
    description: "Steam API key used to interact with the Steam web API"
    required: true
    default: ${{ secrets.STEAM_API_KEY }}
  workshop_items:
    description: "Steam Workshop items and optionally URLs to their source"
    required: true

runs:
  using: "node12"
  main: "index.js"