name: "Steam Workshop Workflow"
author: "TechnologicNick"
description: "Update a README with information about Steam Workshop items"

inputs:
  steam_api_key:
    description: "Steam API key used to interact with the Steam web API"
    required: true
  comment_tag:
    description: "The comment tags to look for: <!-- comment_tag:START --> and <!-- comment_tag:END -->"
    required: false
    default: "WORKSHOP-SHOWCASE"
  readme_file:
    description: "The path to the README file"
    required: false
    default: "README.md"
  image_path:
    description: "The path to the folder of generated images"
    required: false
    default: "media/steam-workshop-workflow/"
  icon_steam:
    description: "The URL to the Steam icon"
    required: true
    default: "https://raw.githubusercontent.com/TechnologicNick/steam-workshop-workflow/master/steam_icon_black.svg,36,36"
  workshop_items:
    description: "Steam Workshop items and optionally URLs to their source"
    required: true

runs:
  using: "node20"
  main: "index.js"